---

# User RHPDS AAP Open Environment
# https://learn.microsoft.com/en-us/azure/developer/ansible/vm-configure?tabs=ansible

- name: Create Resource Group {{ rg }}
  azure.azcollection.azure_rm_resourcegroup:
    name: "{{ item.name }}"
    location: "{{ item.location }}"
    state: present
  loop: "{{ rg }}"
  #register: rg

- name: Create Vnet {{ vnet }}
  azure.azcollection.azure_rm_virtualnetwork:
    name: "{{ item.name }}"
    resource_group: "{{ item.rg }}"
    #location: "{{ vnet.location }}"
    address_prefixes_cidr: "{{ item.cidr }}"
    state: present
  loop: "{{ vnet }}"
  #register: vnet

- name: Create Subnet {{ subnet }}
  azure.azcollection.azure_rm_subnet:
    name: "{{ item.name }}"
    resource_group: "{{ item.rg }}"
    virtual_network: "{{ item.vnet }}"
    #location: "{{ item.location }}"
    address_prefix_cidr: "{{ item.cidr }}"
    state: present
  loop: "{{ subnet }}"
  #register: subnet

- name: Create Security Group {{ sg }}
  azure.azcollection.azure_rm_securitygroup:
    name: "{{ item.name }}"
    resource_group: "{{ item.rg }}"
    rules:
      - name: AllowOpenPorts
        priority: 100
        protocol: Tcp
        source_address_prefix: 0.0.0.0/0
        destination_port_range: "{{ item.openports }}"
        access: Allow
        direction: Inbound
    state: present
  loop: "{{ sg }}"
  #register: sg

- name: Create Public IP {{ pip }}
  azure.azcollection.azure_rm_publicipaddress:
    name: "{{ item.name }}"
    resource_group: "{{ item.rg }}"
    allocation_method: "{{ item.method }}"
    state: present
  loop: "{{ pip }}"
  register: pip_out

# - name: Public IP of VM
#   debug:
#     msg: "The public IP is {{ pip.state.ip_address }}"

- name: Create Network Interface {{ interface }}
  azure.azcollection.azure_rm_networkinterface:
    name: "{{ item.name }}"
    resource_group: "{{ item.rg }}"
    virtual_network: "{{ item.vnet }}"
    subnet_name: "{{ item.subnet }}"
    security_group: "{{ item.sg }}"
    ip_configurations:
      - name: eth
        public_ip_address_name: "{{ item.pip }}"
        primary: True
    state: present
  loop: "{{ interface }}"
  #register: interface

- name: Create RHEL VM {{ vm }}
  azure.azcollection.azure_rm_virtualmachine:
    name: "{{ item.name }}"
    resource_group: "{{ item.rg }}"
    virtual_network_name: "{{ item.vnet }}"
    subnet_name: "{{ item.subnet }}"
    vm_size: "{{ item.flavor }}"
    admin_username: "{{ item.admin_username }}"
    admin_password: "{{ item.admin_password }}"
    network_interface_names: "{{ item.interface }}"
    os_type: "{{ item.os_type }}"
    ssh_public_keys:
      - path: "/home/{{ admin_username }}/.ssh/authorized_keys"
        key_data: "{{ public_key }}"
    image: "{{ item.image }}"
    started: "{{ item.started }}"
    state: present
  loop: "{{ vm }}"
  #register: vm

- debug:
    var: pip_out

- name: Wait for port 22 to become open
  connection: local
  wait_for:
    host: "{{ item.state.ip_address }}"
    port: 22
    timeout: 300
    delay: 10
  loop: "{{ pip_out.results }}"