---
# https://learn.microsoft.com/en-us/azure/developer/ansible/vm-configure?tabs=ansible
- name: Delete RHEL VM
  azure.azcollection.azure_rm_virtualmachine:
    name: "{{ instance_name }}"
    resource_group: "{{ rg_name }}"
    remove_on_absent: all_autocreated
    state: absent
  register: vm

- name: Delete Network Interface
  azure.azcollection.azure_rm_networkinterface:
    name: "{{ instance_name }}"
    resource_group: "{{ rg_name }}"
    state: absent
  register: interface

- name: Delete Public IP
  azure.azcollection.azure_rm_publicipaddress:
    name: "{{ public_ip }}"
    resource_group: "{{ rg_name }}"
    state: absent
  register: public_ip
  ignore_errors: true

- name: Delete Security Group
  azure.azcollection.azure_rm_securitygroup:
    name: "{{ sg_name }}"
    resource_group: "{{ rg_name }}"
    state: absent
  register: sg

- name: Delete Subnet in VNet
  azure.azcollection.azure_rm_subnet:
    name: "{{ subnet_name }}"
    resource_group: "{{ rg_name }}"
    virtual_network_name: "{{ vnet_name }}"
    state: absent
  register: subnet

- name: Delete Vnet {{ vnet_name }}
  azure.azcollection.azure_rm_virtualnetwork:
    name: "{{ vnet_name }}"
    resource_group: "{{ rg_name }}"
    state: absent
  register: vnet

# - name: Delete Resource Group {{ rg_name }} and all inner resources
#   azure.azcollection.azure_rm_resourcegroup:
#     name: "{{ rg_name }}"
#     force_delete_nonempty: yes
#     state: absent
#   register: rg
