---

# https://learn.microsoft.com/en-us/azure/developer/ansible/vm-configure?tabs=ansible
- name: Delete RHEL VM {{ vm }}
  azure.azcollection.azure_rm_virtualmachine:
    name: "{{ item.name }}"
    resource_group: "{{ item.rg }}"
    remove_on_absent: all
    state: absent
  loop: "{{ vm }}"
  #register: vm

- name: Delete Network Interface {{ interface }}
  azure.azcollection.azure_rm_networkinterface:
    name: "{{ item.name }}"
    resource_group: "{{ item.rg }}"
    state: absent
  register: interface
  until: "interface is not failed"
  retries: 4
  delay: 60
  loop: "{{ interface }}"

- name: Delete Public IP {{ pip }}
  azure.azcollection.azure_rm_publicipaddress:
    name: "{{ item.name }}"
    resource_group: "{{ item.rg }}"
    state: absent
  loop: "{{ pip }}"

- name: Delete Security Group {{ sg }}
  azure.azcollection.azure_rm_securitygroup:
    name: "{{ item.name }}"
    resource_group: "{{ item.rg }}"
    state: absent
  loop: "{{ sg }}"
  #register: sg

- name: Delete Subnet {{ subnet }}
  azure.azcollection.azure_rm_subnet:
    name: "{{ item.name }}"
    resource_group: "{{ item.rg }}"
    virtual_network_name: "{{ item.vnet }}"
    state: absent
  loop: "{{ subnet }}"
  #register: subnet

- name: Delete Vnet {{ vnet }}
  azure.azcollection.azure_rm_virtualnetwork:
    name: "{{ item.name }}"
    resource_group: "{{ item.rg }}"
    state: absent
  loop: "{{ vnet }}"
  #register: vnet

- name: Delete Resource Group {{ rg }} and all inner resources
  azure.azcollection.azure_rm_resourcegroup:
    name: "{{ item.name }}"
    force_delete_nonempty: yes
    state: absent
  loop: "{{ rg }}"
  #register: rg
