---

- name: Delete Resource Group {{ rg_name }} and all inner resources
  azure.azcollection.azure_rm_resourcegroup:
    name: "{{ rg_name }}"
    force_delete_nonempty: yes
    state: absent
  register: rg
