---

# https://learn.microsoft.com/en-us/azure/developer/ansible/vm-configure?tabs=ansible
- name: Delete RHEL VM {{ instance_name }}
  azure.azcollection.azure_rm_virtualmachine:
    name: "{{ instance_name }}"
    resource_group: "{{ rg_name }}"
    remove_on_absent: all
    state: absent
  register: vm

- name: Delete Network Interface {{ interface_name }}
  azure.azcollection.azure_rm_networkinterface:
    name: "{{ interface_name }}"
    resource_group: "{{ rg_name }}"
    state: absent
  register: interface
  until: "interface is not failed"
  retries: 4
  delay: 60

- name: Delete Public IP {{ public_ip }}
  azure.azcollection.azure_rm_publicipaddress:
    name: "{{ public_ip }}"
    resource_group: "{{ rg_name }}"
    state: absent
  register: pip

- name: Delete Security Group {{ sg_name }}
  azure.azcollection.azure_rm_securitygroup:
    name: "{{ sg_name }}"
    resource_group: "{{ rg_name }}"
    state: absent
  register: sg

- name: Delete Subnet {{ subnet_name }}
  azure.azcollection.azure_rm_subnet:
    name: "{{ subnet_name }}"
    resource_group: "{{ rg_name }}"
    virtual_network_name: "{{ vnet_name }}"
    state: absent
  register: subnet

- name: Delete Vnet {{ vnet_name }}
  azure.azcollection.azure_rm_virtualnetwork:
    name: "{{ vnet_name }}"
    resource_group: "{{ rg_name }}"
    state: absent
  register: vnet

- name: Delete Resource Group {{ rg_name }} and all inner resources
  azure.azcollection.azure_rm_resourcegroup:
    name: "{{ rg_name }}"
    force_delete_nonempty: yes
    state: absent
  register: rg
