# VPC
ec2_vpc_name: VPC1
ec2_vpc_region: eu-central-1
ec2_vpc_cidr: 10.0.0.0/16
# Subnet
ec2_subnet_name: Subnet1
ec2_subnet_cidr: 10.0.0.0/24
# IGW
ec2_igw_name: IGW1
# Route Table
ec2_rt_name: RT1
# RHEL Open ports
ec2_sg_name: SG1
ec2_sg_openports:
  - 80
  - 443
  - 22
# AMI
ec2_image_name: RHEL-8.6.0_HVM-*x86_64*
# Flavour 
ec2_flavor_name: t2.micro
# Disk
ec2_disk_size: 20
ec2_ebs_name: /dev/sda1
# Key Pair
ec2_key_name: "KeyPair"
# Instance
ec2_instance_name: rhel-1
