#
# Using blank env
# change the rg_name var
# On AAP Azure Credential change (form demo-redhat.com Advanced settings)
# # Subscription ID (azure_subscription)
# # Client ID (azure_service_principal_id)
# # Client Secret (azure_service_principal_password)
#

# Resource Group
rg_name: cparada-rhel
#rg_location: 
# VNet
vnet_name: VNet1
vnet_location: eastus
vnet_cidr: 10.0.0.0/16
# Subnet
subnet_name: Subnet1
subnet_cidr: 10.0.0.0/24
# Public IP
public_ip: pip1
# Interface card
interface_name: interface1
# RHEL Open ports
sg_name: SG1
sg_openports:
  - 80
  - 443
  - 22
# AMI
image_name: RHEL-8.6.0_HVM-*x86_64*
# auth
admin_username: adminuser
admin_password: rhelpass
# Flavour 
flavor_name: Standard_D2s_v3
#flavor_name: D2s_v3
# Disk
disk_size: 20
ebs_name: /dev/sda1
# Key Pair
key_name: "KeyPair"
# Instance
instance_name: rhel-1
